# Autogenerated by maintainers/scripts/bootstrap-files/refresh-tarballs.bash as:
# $ ./refresh-tarballs.bash --targets=s390x-unknown-linux-gnu
#
# Metadata:
# - nixpkgs revision: 00b9fc64d8b8765731cdb2e93312b8cb5c89c517
# - hydra build: https://hydra.nixos.org/job/nixpkgs/cross-trunk/bootstrapTools.s390x-unknown-linux-gnu.build/latest
# - resolved hydra build: https://hydra.nixos.org/build/267278496
# - instantiated derivation: /nix/store/x3il6s0nqx44bq1v3c0alf1c04gpgndc-stdenv-bootstrap-tools-s390x-unknown-linux-gnu.drv
# - output directory: /nix/store/zbkj96lsqf9mby2cxa23qqi30a9yr2i2-stdenv-bootstrap-tools-s390x-unknown-linux-gnu
# - build time: Mon, 22 Jul 2024 08:21:21 +0000
{
  bootstrapTools = import <nix/fetchurl.nix> {
    url = "http://tarballs.nixos.org/stdenv/s390x-unknown-linux-gnu/00b9fc64d8b8765731cdb2e93312b8cb5c89c517/bootstrap-tools.tar.xz";
    hash = "sha256-JUFnjEYzlDh1eZRFCyKGwcF3wjEnJuu/xVFUaA2txPk=";
  };
  busybox = import <nix/fetchurl.nix> {
    url = "http://tarballs.nixos.org/stdenv/s390x-unknown-linux-gnu/00b9fc64d8b8765731cdb2e93312b8cb5c89c517/busybox";
    hash = "sha256-Uq0nJauX4Q8zoVrFG5oDzGNTiF4Drwv0g92tZYFLzWo=";
    executable = true;
  };
}
